AWSTemplateFormatVersion: '2010-09-09'
Description: A simple function.
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - FunctionRole
          - Arn
      Runtime: nodejs16.x
      Code:
        ZipFile:
          Fn::Sub: |
            exports.handler = async (event, context) => {
                return {
                        'statusCode': 200,
                        'body': JSON.stringify({
                            message: 'hello world!!! I\'m RGM.',
                        })
                    };
            };
Outputs:
  FunctionArn:
    Value:
      Fn::GetAtt:
        - Function
        - Arn
