AWSTemplateFormatVersion: '2010-09-09'
Description: A simple function.
Parameters:
  Name:
    Type: String
  RoleNameRoleParameter:
    Type: String
    Default: ItamarTestRole
Resources:
  TestRole:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles: ['ItamarTestRole']
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - TestRole
          - Arn
      Runtime: nodejs16.x
      Code:
        ZipFile:
          Fn::Sub: |
            exports.handler = async (event, context) => {
                return {
                        'statusCode': 200,
                        'body': JSON.stringify({
                            message: 'hello world!!! I\'m ${Name}.',
                        })
                    };
            };
Outputs:
  FunctionArn:
    Value:
      Fn::GetAtt:
        - Function
        - Arn
